version: "3.1"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - db
    links:
      - db

  db:
    # container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./pokeData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Pokemon
    ports:
      - 27017:27017
